"""Orders Table

Revision ID: d2e8cf6703da
Revises: None
Create Date: 2017-05-30 16:14:22.917789

"""

# revision identifiers, used by Alembic.
revision = 'd2e8cf6703da'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('number_of_pages', sa.Integer(), nullable=True),
    sa.Column('number_of_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    ### end Alembic commands ###
